test: &default

  # Credentials for REST APIs
  client_id: AVxtyueLXuHH7ErPazQYZKQ4UurZfdLlrksHhITEhJNRw37tRBHRCSzN7ltI64R-sr1h3-GMvd1DYz7M
  client_secret: EG4wGOTK88kPC6Vyw2qloRTUwIOE6ObRPszDFRokLp3hOgeCfW5v-K_wm-UsQM1lVFZoMs_hWEQyTY4q

  # Mode can be 'live' or 'sandbox'
  mode: sandbox

  # Credentials for Classic APIs
  app_id: APP-80W284485P519543T
  username: payment-facilitator_api1.day.com.my
  password: 447XSKQF9HXG5SDL
  signature: AFcWxV21C7fd0v3bYYYRCpSSRl31AHE-WR3TI-jQifaZbe3zgabDdGHd
  # # With Certificate
  # cert_path: "config/cert_key.pem"
  sandbox_email_address: xuxianzhi-facilitator@me.com

  # # IP Address
  # ip_address: 127.0.0.1
  # # HTTP Proxy
  # http_proxy: http://proxy-ipaddress:3129/

development:
  <<: *default

production:
  <<: *default
  mode: live
