test: &default

  # Credentials for REST APIs
  client_id: AZauUFULswDFIiY_A8luAnAU37m8oz06xuwvqQMJ992WNwPG9yPgd0FiMb4A0bLSUZYJu6lZtMhXSBzS
  client_secret: EBQVu345CJHGstixeF8QEst22B9J6znHbZuYAvNIW0IVHd3YS-clMCce84yRrO2Glo6-KLiw5SzMtTBd

  # Mode can be 'live' or 'sandbox'
  mode: sandbox

  # Credentials for Classic APIs
  app_id: APP-80W284485P519543T
  username: itsjinlie-facilitator_api1.hotmail.com
  password: BWFRJLCTQQ58WFJ9
  signature: An5ns1Kso7MWUdW4ErQKJJJ4qi4-A-.I2OfKc.hbMrsyQ5po718H-F28
  # # With Certificate
  # cert_path: "config/cert_key.pem"
  sandbox_email_address: itsjinlie-facilitator@hotmail.com

  # # IP Address
  # ip_address: 127.0.0.1
  # # HTTP Proxy
  # http_proxy: http://proxy-ipaddress:3129/

development:
  <<: *default

production:
  <<: *default
  mode: live
